/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PdfRouteImport } from './routes/pdf'
import { Route as ImageRouteImport } from './routes/image'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as ApiUsageWorkerRouteImport } from './routes/api/usage-worker'
import { Route as ApiSubscriptionCheckRouteImport } from './routes/api/subscription-check'
import { Route as ApiMemoryWorkerRouteImport } from './routes/api/memory-worker'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfRoute = PdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageWorkerRoute = ApiUsageWorkerRouteImport.update({
  id: '/api/usage-worker',
  path: '/api/usage-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionCheckRoute = ApiSubscriptionCheckRouteImport.update({
  id: '/api/subscription-check',
  path: '/api/subscription-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryWorkerRoute = ApiMemoryWorkerRouteImport.update({
  id: '/api/memory-worker',
  path: '/api/memory-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/image': typeof ImageRoute
  '/pdf': typeof PdfRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/memory-worker': typeof ApiMemoryWorkerRoute
  '/api/subscription-check': typeof ApiSubscriptionCheckRoute
  '/api/usage-worker': typeof ApiUsageWorkerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/image': typeof ImageRoute
  '/pdf': typeof PdfRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/memory-worker': typeof ApiMemoryWorkerRoute
  '/api/subscription-check': typeof ApiSubscriptionCheckRoute
  '/api/usage-worker': typeof ApiUsageWorkerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/image': typeof ImageRoute
  '/pdf': typeof PdfRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/memory-worker': typeof ApiMemoryWorkerRoute
  '/api/subscription-check': typeof ApiSubscriptionCheckRoute
  '/api/usage-worker': typeof ApiUsageWorkerRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/history'
    | '/image'
    | '/pdf'
    | '/premium'
    | '/profile'
    | '/api/ai-chat'
    | '/api/generate-image'
    | '/api/memory-worker'
    | '/api/subscription-check'
    | '/api/usage-worker'
    | '/auth/callback'
    | '/chat/$threadId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/history'
    | '/image'
    | '/pdf'
    | '/premium'
    | '/profile'
    | '/api/ai-chat'
    | '/api/generate-image'
    | '/api/memory-worker'
    | '/api/subscription-check'
    | '/api/usage-worker'
    | '/auth/callback'
    | '/chat/$threadId'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/history'
    | '/image'
    | '/pdf'
    | '/premium'
    | '/profile'
    | '/api/ai-chat'
    | '/api/generate-image'
    | '/api/memory-worker'
    | '/api/subscription-check'
    | '/api/usage-worker'
    | '/auth_/callback'
    | '/chat/$threadId'
    | '/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  ImageRoute: typeof ImageRoute
  PdfRoute: typeof PdfRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiMemoryWorkerRoute: typeof ApiMemoryWorkerRoute
  ApiSubscriptionCheckRoute: typeof ApiSubscriptionCheckRoute
  ApiUsageWorkerRoute: typeof ApiUsageWorkerRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf': {
      id: '/pdf'
      path: '/pdf'
      fullPath: '/pdf'
      preLoaderRoute: typeof PdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage-worker': {
      id: '/api/usage-worker'
      path: '/api/usage-worker'
      fullPath: '/api/usage-worker'
      preLoaderRoute: typeof ApiUsageWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscription-check': {
      id: '/api/subscription-check'
      path: '/api/subscription-check'
      fullPath: '/api/subscription-check'
      preLoaderRoute: typeof ApiSubscriptionCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory-worker': {
      id: '/api/memory-worker'
      path: '/api/memory-worker'
      fullPath: '/api/memory-worker'
      preLoaderRoute: typeof ApiMemoryWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  ImageRoute: ImageRoute,
  PdfRoute: PdfRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiMemoryWorkerRoute: ApiMemoryWorkerRoute,
  ApiSubscriptionCheckRoute: ApiSubscriptionCheckRoute,
  ApiUsageWorkerRoute: ApiUsageWorkerRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
